# Generated by Django 4.1.3 on 2022-11-21 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_address_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='publisher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='book.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(5, 'code cannot be less than a length of 5'), django.core.validators.MaxLengthValidator(6, 'code cannot exceed length of 6')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
